### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by itldg** [WTPP/Android-USB-Arduino-M5Stack-Maui#2]
It did not run successfully on my mobile phone, indicating an error.

![1671607817849](https://user-images.githubusercontent.com/13432299/208848009-e130abc9-6987-4af0-a7ff-946385f5b2d8.png)

```
com.companyname.mauiatom: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

**Comment by itldg** [comment]
Xiaomi M2011K2C (Android 13.0 API 33)

This is my mobile phone model

**Comment by WTPP** [comment]
at what point was the exception thrown?

**Comment by itldg** [comment]
When the program just started

**Comment by WTPP** [comment]
debug it to see at which line it breaks

**Comment by itldg** [comment]
An error was raised on line 34.

**Comment by itldg** [comment]
An error was raised on line 31.

![image](https://user-images.githubusercontent.com/13432299/208850116-96f9f88e-0d31-4d3d-b14e-f84d97fdd2f0.png)

**Comment by itldg** [comment]
I tested it on another mobile phone and made an error.

Xiaomi Redmi 6A (Android 9.0 API 28)

This mobile phone does not support wireless debugging, so I added a pop-up window.

![4ba951b1cb9748c1ab1a4cfbad2e25c](https://user-images.githubusercontent.com/13432299/208855584-318edf1e-b01c-409e-8f0a-c7bc6361f69f.jpg)



```
Specified argument was out of the range of valid values. (Parameter 'index')
```

**Comment by itldg** [comment]
The problem should be here, this array is empty

![image](https://user-images.githubusercontent.com/13432299/208856653-db844edd-e75b-4456-b013-583d7430e553.png)

**Comment by WTPP** [comment]
available driver array is empty on both phones? Do you use wireless debug on first phone? I had the same issue with availabledrivers being empty, but it was before I used wireless debug. After I connect my phone via wireless debug and connect atom via usb to phone, availabledrivers was populated

**Comment by itldg** [comment]
> available driver array is empty on both phones? Do you use wireless debug on first phone? I had the same issue with availabledrivers being empty, but it was before I used wireless debug. After I connect my phone via wireless debug and connect atom via usb to phone, availabledrivers was populated

Yes, I am using a mobile phone that supports wireless debugging.

manager.DeviceList count:1

UsbSerialProber.DefaultProber.FindAllDrivers(manager); count:0

**Comment by itldg** [comment]
I am using CH340, is it because there is no device_filter?

**Comment by itldg** [comment]
```
IList<IUsbSerialDriver> availableDrivers = UsbSerialProber.DefaultProber.FindAllDrivers(manager);
```
Modified as

```
ProbeTable customTable = new ProbeTable();
Java.Lang.Class cdcAcmClass = Java.Lang.Class.FromType(typeof(CdcAcmSerialDriver));
customTable.AddProduct(device.VendorId, device.ProductId, cdcAcmClass);
UsbSerialProber prober = new UsbSerialProber(customTable);
var availableDrivers = prober.FindAllDrivers(manager);
```

This problem can be solved, but new problems have arisen

```
_port.Open(connection);
```

![image](https://user-images.githubusercontent.com/13432299/209045437-71ece296-e329-431c-90b1-836b699918ba.png)

```
{Java.Lang.ArrayIndexOutOfBoundsException: length=1; index=1
   at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:line 11884
   at Android.Runtime.JNIEnv.CallVoidMethod(IntPtr jobject, IntPtr jmethod, JValue* parms) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.g.cs:line 264
   at Android.Runtime.JNIEnv.CallVoidMethod(IntPtr jobject, IntPtr jmethod, JValue[] parms) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.g.cs:line 270
   at Hoho.Android.UsbSerial.Driver.CdcAcmSerialDriver.CdcAcmSerialPort.Open(UsbDeviceConnection p0)
   at MauiATOM.MainPage.Connect() in F:\Data\Code\Git\Android-USB-Arduino-M5Stack-Maui\MauiATOM\MainPage.xaml.cs:line 64
  --- End of managed Java.Lang.ArrayIndexOutOfBoundsException stack trace ---
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at android.hardware.usb.UsbDevice.getInterface(UsbDevice.java:307)
	at com.hoho.android.usbserial.driver.CdcAcmSerialDriver$CdcAcmSerialPort.open(CdcAcmSerialDriver.java:122)
	at crc640ec207abc449b2ca.ShellSectionRenderer.n_onCreateView(Native Method)
	at crc640ec207abc449b2ca.ShellSectionRenderer.onCreateView(ShellSectionRenderer.java:42)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1544)
	at android.app.Activity.performStart(Activity.java:8548)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3842)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8237)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

  --- End of managed Java.Lang.ArrayIndexOutOfBoundsException stack trace ---
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at android.hardware.usb.UsbDevice.getInterface(UsbDevice.java:307)
	at com.hoho.android.usbserial.driver.CdcAcmSerialDriver$CdcAcmSerialPort.open(CdcAcmSerialDriver.java:122)
	at crc640ec207abc449b2ca.ShellSectionRenderer.n_onCreateView(Native Method)
	at crc640ec207abc449b2ca.ShellSectionRenderer.onCreateView(ShellSectionRenderer.java:42)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1544)
	at android.app.Activity.performStart(Activity.java:8548)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3842)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8237)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
}
```

**Comment by itldg** [comment]
![image](https://user-images.githubusercontent.com/13432299/209068974-a988c636-41ec-4559-bb3d-7ebb2f974f59.png)
![image](https://user-images.githubusercontent.com/13432299/209069029-bc098ee4-adc5-476f-9b32-42ed329321d1.png)
Can close the post, I changed a FT serial port, everything is normal

It should be that the version of this library is too low and does not support CH340. I have to think of other ways.

**Comment by itldg** [comment]
https://github.com/itldg/MauiUsbSerialForAndroid

I finally finished, thank you
